// import "./globals.css";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type LayoutProps = {
  children: React.ReactNode;
}
// 同层级 page 会作为 children 参数传入 layout
export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <div>setting-layout</div>
      <div>{children}</div>
    </>
  );
}
